import CinemaProvider from '../context';
import Head from 'next/head';

import '../styles/globals.css';
import '../styles/home.css';


function MyApp({ Component, pageProps }) {
  return (
    <CinemaProvider>
      <Head>
        <title>Cineplex</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg"/>
      </Head>
      <Component {...pageProps} />
    </CinemaProvider>
  );
}

export default MyApp;
