import dynamic from 'next/dynamic';
import CinemaProvider from '../context';
import Head from 'next/head';
import '../styles/globals.css';
import './home.css';

const Tab = dynamic(() => import('../components/tab'));
const Navbar = dynamic(() => import('../components/navbar'));

function MyApp({ Component, pageProps }) {
  return (
    <CinemaProvider>
      <Head>
        <title>Cineplex</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg"/>
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Tab />
    </CinemaProvider>
  );
}

export default MyApp;
