import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  const cities = ['Tumbaco', 'Los Chillos', 'Cayambe', 'El Coca'];
  const posters = [
    'https://www.cineplex.com.ec/customers/fotos/poster_coda.jpg',
    'https://www.cineplex.com.ec/customers/fotos/poster_huevitos.jpg',
    'https://www.cineplex.com.ec/customers/fotos/poster_lacasaoscura2.jpg',
    'https://www.cineplex.com.ec/customers/fotos/poster_007.jpg',
    'https://www.cineplex.com.ec/customers/fotos/poster_venom3.jpg',
  ];
  return (
    <div>
      <Head>
        <title>Cinema app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container px-3 py-5'>
        <div className='text-center'>
          {cities.map((city, i) => (
            <button
              key={`btn-city-${i}`}
              className='rounded-full border border-black px-3 py-1 mr-3 mb-3 focus:bg-black focus:text-white'
            >
              {city}
            </button>
          ))}
        </div>
        <div className='my-5 text-center grid grid-cols-2 gap-3'>
          {posters.map((poster, i) => (
            <Image
              src={poster}
              key={`poster-${i}`}
              alt={`poster-${i}`}
              height={300}
              width={150}
              objectFit='cover'
              className='my-image rounded-lg'
            />
          ))}
        </div>
      </main>
    </div>
  );
}
